recurring_events.eventseries.config:
  type: config_object
  label: 'Recurring Events Series Config'
  mapping:
    interval:
      type: integer
      label: 'The interval between times when creating event series'
    min_time:
      type: string
      label: 'The earliest an event can start'
    max_time:
      type: string
      label: 'The latest an event can start'
    date_format:
      type: string
      label: 'The formatting of dates when displaying event series'
    time_format:
      type: string
      label: 'The formatting of times when creating event series'
    days:
      type: string
      label: 'The days of the week available when creating event series'
    limit:
      type: integer
      label: 'The items per page to show on event series listing'
    excludes:
      type: integer
      label: 'Enable eventseries level excluded dates'
    includes:
      type: integer
      label: 'Enable eventseries level included dates'
    enabled_fields:
      type: string
      label: 'Which recur type fields are available in the creation form'
    threshold_warning:
      type: integer
      label: 'Show a warning when too many event instances are being created'
    threshold_count:
      type: integer
      label: 'The number of event instances to trigger the warning'
    threshold_message:
      type: string
      label: 'The warning to show when too many instances are being created'
    threshold_prevent_save:
      type: integer
      label: 'Prevent saving a series if too many instances are being created'

recurring_events.eventinstance.config:
  type: config_object
  label: 'Recurring Events Instance Config'
  mapping:
    date_format:
      type: string
      label: 'The formatting of dates when displaying event instances'
    limit:
      type: integer
      label: 'The items per page to show on event instance listing'

field.formatter.settings.recurring_events_eventinstance_date:
  type: mapping
  label: 'Recurring Events Event Instance Date Formatter'
  mapping:
    link:
      type: string
      label: 'Whether to format the date as a link'
    date_format:
      type: string
      label: 'The date format to use to display the date'
    separator:
      type: string
      label: 'The separator to use between start and end dates'
