recurring_events.eventseries.config:
  type: config_object
  label: 'Recurring Events Series Config'
  mapping:
    interval:
      type: integer
      label: 'The interval between times when creating events'
    min_time:
      type: string
      label: 'The earliest an event can start'
    max_time:
      type: string
      label: 'The latest an event can start'
    time_format:
      type: string
      label: 'The formatting of times when creating events'
    days:
      type: string
      label: 'The days of the week available when creating events'