recurring_events_registration.registrant.config:
  type: config_object
  label: 'Recurring Events Registration Config'
  mapping:
    show_capacity:
      type: boolean
      label: 'Whether to display the remaining capacity for an event during registration'
    limit:
      type: integer
      label: 'The items per page to show on registrant listing'
    date_format:
      type: string
      label: 'The formatting of dates when displaying registrants'
    email_notifications:
      type: boolean
      label: 'Whether to enable email notifications'
    registration_notification_enabled:
      type: boolean
      label: 'Whether to enable registration email notifications'
    registration_notification_subject:
      type: string
      label: 'The email subject for the registration emails'
    registration_notification_body:
      type: string
      label: 'The email body for the registration emails'
    waitlist_notification_enabled:
      type: boolean
      label: 'Whether to enable waitlist email notifications'
    waitlist_notification_subject:
      type: string
      label: 'The email subject for the waitlist emails'
    waitlist_notification_body:
      type: string
      label: 'The email body for the waitlist emails'
    promotion_notification_enabled:
      type: boolean
      label: 'Whether to enable promotion email notifications'
    promotion_notification_subject:
      type: string
      label: 'The email subject for the promotion emails'
    promotion_notification_body:
      type: string
      label: 'The email body for the promotion emails'
    cancellation_notification_enabled:
      type: boolean
      label: 'Whether to enable cancellation email notifications'
    cancellation_notification_subject:
      type: string
      label: 'The email subject for the cancellation emails'
    cancellation_notification_body:
      type: string
      label: 'The email body for the cancellation emails'
    modification_notification_enabled:
      type: boolean
      label: 'Whether to enable modification email notifications'
    modification_notification_subject:
      type: string
      label: 'The email subject for the modification emails'
    modification_notification_body:
      type: string
      label: 'The email body for the modification emails'
